name: Push PageUI

on:
  push:
    branches:
      - main # Adjust branch as needed

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes all PageUI templates to PageAI
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: '/'
          destination-branch: 'main'
          destination-username: 'danmindru'
          destination-repository: 'page-ai'
          destination-directory: 'packages/api/page-ui'
          commit-email: 'action@github.com'
          commit-username: 'danmindru'
          commit-message: '🔄 Sync Page UI'
